//
//  CommerceSymbols.swift
//  
//
//  Created by Donavon Buchanan on 9/13/20.
//

@available(OSX 11.0, iOS 14.0, tvOS 14.0, watchOS 7.0, *)
extension SFSymbols {
    //MARK: - Commerce
    enum Commerce: String, CaseIterable, Identifiable {
        var id: String { rawValue }
        
        case signature = "signature"
        case bag = "bag"
        case bagFill = "bag.fill"
        case bagBadgePlus = "bag.badge.plus"
        case bagFillBadgePlus = "bag.fill.badge.plus"
        case bagBadgeMinus = "bag.badge.minus"
        case bagFillBadgeMinus = "bag.fill.badge.minus"
        case cart = "cart"
        case cartFill = "cart.fill"
        case cartBadgePlus = "cart.badge.plus"
        case cartFillBadgePlus = "cart.fill.badge.plus"
        case cartBadgeMinus = "cart.badge.minus"
        case cartFillBadgeMinus = "cart.fill.badge.minus"
        case creditcard = "creditcard"
        case creditcardFill = "creditcard.fill"
        case dollarsignCircle = "dollarsign.circle"
        case dollarsignCircleFill = "dollarsign.circle.fill"
        case centsignCircle = "centsign.circle"
        case centsignCircleFill = "centsign.circle.fill"
        case yensignCircle = "yensign.circle"
        case yensignCircleFill = "yensign.circle.fill"
        case sterlingsignCircle = "sterlingsign.circle"
        case sterlingsignCircleFill = "sterlingsign.circle.fill"
        case francsignCircle = "francsign.circle"
        case francsignCircleFill = "francsign.circle.fill"
        case florinsignCircle = "florinsign.circle"
        case florinsignCircleFill = "florinsign.circle.fill"
        case turkishlirasignCircle = "turkishlirasign.circle"
        case turkishlirasignCircleFill = "turkishlirasign.circle.fill"
        case rublesignCircle = "rublesign.circle"
        case rublesignCircleFill = "rublesign.circle.fill"
        case eurosignCircle = "eurosign.circle"
        case eurosignCircleFill = "eurosign.circle.fill"
        case dongsignCircle = "dongsign.circle"
        case dongsignCircleFill = "dongsign.circle.fill"
        case indianrupeesignCircle = "indianrupeesign.circle"
        case indianrupeesignCircleFill = "indianrupeesign.circle.fill"
        case tengesignCircle = "tengesign.circle"
        case tengesignCircleFill = "tengesign.circle.fill"
        case pesetasignCircle = "pesetasign.circle"
        case pesetasignCircleFill = "pesetasign.circle.fill"
        case pesosignCircle = "pesosign.circle"
        case pesosignCircleFill = "pesosign.circle.fill"
        case kipsignCircle = "kipsign.circle"
        case kipsignCircleFill = "kipsign.circle.fill"
        case wonsignCircle = "wonsign.circle"
        case wonsignCircleFill = "wonsign.circle.fill"
        case lirasignCircle = "lirasign.circle"
        case lirasignCircleFill = "lirasign.circle.fill"
        case australsignCircle = "australsign.circle"
        case australsignCircleFill = "australsign.circle.fill"
        case hryvniasignCircle = "hryvniasign.circle"
        case hryvniasignCircleFill = "hryvniasign.circle.fill"
        case nairasignCircle = "nairasign.circle"
        case nairasignCircleFill = "nairasign.circle.fill"
        case guaranisignCircle = "guaranisign.circle"
        case guaranisignCircleFill = "guaranisign.circle.fill"
        case coloncurrencysignCircle = "coloncurrencysign.circle"
        case coloncurrencysignCircleFill = "coloncurrencysign.circle.fill"
        case cedisignCircle = "cedisign.circle"
        case cedisignCircleFill = "cedisign.circle.fill"
        case cruzeirosignCircle = "cruzeirosign.circle"
        case cruzeirosignCircleFill = "cruzeirosign.circle.fill"
        case tugriksignCircle = "tugriksign.circle"
        case tugriksignCircleFill = "tugriksign.circle.fill"
        case millsignCircle = "millsign.circle"
        case millsignCircleFill = "millsign.circle.fill"
        case sheqelsignCircle = "sheqelsign.circle"
        case sheqelsignCircleFill = "sheqelsign.circle.fill"
        case manatsignCircle = "manatsign.circle"
        case manatsignCircleFill = "manatsign.circle.fill"
        case rupeesignCircle = "rupeesign.circle"
        case rupeesignCircleFill = "rupeesign.circle.fill"
        case bahtsignCircle = "bahtsign.circle"
        case bahtsignCircleFill = "bahtsign.circle.fill"
        case larisignCircle = "larisign.circle"
        case larisignCircleFill = "larisign.circle.fill"
        case bitcoinsignCircle = "bitcoinsign.circle"
        case bitcoinsignCircleFill = "bitcoinsign.circle.fill"
        case dollarsignSquare = "dollarsign.square"
        case dollarsignSquareFill = "dollarsign.square.fill"
        case centsignSquare = "centsign.square"
        case centsignSquareFill = "centsign.square.fill"
        case yensignSquare = "yensign.square"
        case yensignSquareFill = "yensign.square.fill"
        case sterlingsignSquare = "sterlingsign.square"
        case sterlingsignSquareFill = "sterlingsign.square.fill"
        case francsignSquare = "francsign.square"
        case francsignSquareFill = "francsign.square.fill"
        case florinsignSquare = "florinsign.square"
        case florinsignSquareFill = "florinsign.square.fill"
        case turkishlirasignSquare = "turkishlirasign.square"
        case turkishlirasignSquareFill = "turkishlirasign.square.fill"
        case rublesignSquare = "rublesign.square"
        case rublesignSquareFill = "rublesign.square.fill"
        case eurosignSquare = "eurosign.square"
        case eurosignSquareFill = "eurosign.square.fill"
        case dongsignSquare = "dongsign.square"
        case dongsignSquareFill = "dongsign.square.fill"
        case indianrupeesignSquare = "indianrupeesign.square"
        case indianrupeesignSquareFill = "indianrupeesign.square.fill"
        case tengesignSquare = "tengesign.square"
        case tengesignSquareFill = "tengesign.square.fill"
        case pesetasignSquare = "pesetasign.square"
        case pesetasignSquareFill = "pesetasign.square.fill"
        case pesosignSquare = "pesosign.square"
        case pesosignSquareFill = "pesosign.square.fill"
        case kipsignSquare = "kipsign.square"
        case kipsignSquareFill = "kipsign.square.fill"
        case wonsignSquare = "wonsign.square"
        case wonsignSquareFill = "wonsign.square.fill"
        case lirasignSquare = "lirasign.square"
        case lirasignSquareFill = "lirasign.square.fill"
        case australsignSquare = "australsign.square"
        case australsignSquareFill = "australsign.square.fill"
        case hryvniasignSquare = "hryvniasign.square"
        case hryvniasignSquareFill = "hryvniasign.square.fill"
        case nairasignSquare = "nairasign.square"
        case nairasignSquareFill = "nairasign.square.fill"
        case guaranisignSquare = "guaranisign.square"
        case guaranisignSquareFill = "guaranisign.square.fill"
        case coloncurrencysignSquare = "coloncurrencysign.square"
        case coloncurrencysignSquareFill = "coloncurrencysign.square.fill"
        case cedisignSquare = "cedisign.square"
        case cedisignSquareFill = "cedisign.square.fill"
        case cruzeirosignSquare = "cruzeirosign.square"
        case cruzeirosignSquareFill = "cruzeirosign.square.fill"
        case tugriksignSquare = "tugriksign.square"
        case tugriksignSquareFill = "tugriksign.square.fill"
        case millsignSquare = "millsign.square"
        case millsignSquareFill = "millsign.square.fill"
        case sheqelsignSquare = "sheqelsign.square"
        case sheqelsignSquareFill = "sheqelsign.square.fill"
        case manatsignSquare = "manatsign.square"
        case manatsignSquareFill = "manatsign.square.fill"
        case rupeesignSquare = "rupeesign.square"
        case rupeesignSquareFill = "rupeesign.square.fill"
        case bahtsignSquare = "bahtsign.square"
        case bahtsignSquareFill = "bahtsign.square.fill"
        case larisignSquare = "larisign.square"
        case larisignSquareFill = "larisign.square.fill"
        case bitcoinsignSquare = "bitcoinsign.square"
        case bitcoinsignSquareFill = "bitcoinsign.square.fill"
    }
}
